[2024-02-18 03:26:46,450] 1758 asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-75' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at C:\Users\DebasisPanigrahy\anaconda3\envs\omsgenai\lib\site-packages\tornado\websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\Users\DebasisPanigrahy\anaconda3\envs\omsgenai\lib\site-packages\tornado\websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DebasisPanigrahy\anaconda3\envs\omsgenai\lib\site-packages\tornado\websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[2024-02-18 03:27:12,924] 1027 httpx - INFO - HTTP Request: POST https://dp0303014.openai.azure.com//openai/deployments/dp140303/completions?api-version=2023-12-01-preview "HTTP/1.1 200 OK"
[2024-02-18 03:27:16,100] 1027 httpx - INFO - HTTP Request: POST https://dp0303014.openai.azure.com//openai/deployments/dp140303/completions?api-version=2023-12-01-preview "HTTP/1.1 200 OK"
[2024-02-18 03:28:12,526] 1027 httpx - INFO - HTTP Request: POST https://dp0303014.openai.azure.com//openai/deployments/dp140303/completions?api-version=2023-12-01-preview "HTTP/1.1 200 OK"
[2024-02-18 03:28:13,823] 1027 httpx - INFO - HTTP Request: POST https://dp0303014.openai.azure.com//openai/deployments/dp140303/completions?api-version=2023-12-01-preview "HTTP/1.1 200 OK"
